Avoid null reference when max size is 1
Previously, when max size was 1, any additions after the first one
would fail with

> TypeError: Cannot set property 'prev' of null

because the `evict` function did not expect there could be nothing left
in the cache once the evicted item was removed.

This change makes the `evict` more robust in cases like that.